# Generated by Django 5.0.7 on 2024-07-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_items_product_order_items_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
    ]
