# Generated by Django 5.0.7 on 2024-08-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_order_items_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.DeleteModel(
            name='Shipping_Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Items',
        ),
    ]
