# Generated by Django 5.0.7 on 2024-08-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0004_remove_order_user_remove_order_items_order_and_more'),
        ('Products', '0004_book_page10_image_book_page11_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tax_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Shipping_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Total_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Is_Delivered', models.BooleanField(default=False)),
                ('Delivered_At', models.DateTimeField(blank=True, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Qty', models.IntegerField(blank=True, default=0, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Image', models.CharField(blank=True, max_length=200, null=True)),
                ('OrderItem_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Address',
            fields=[
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, max_length=200, null=True)),
                ('School_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Shipping_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Shipping_Id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
