# Generated by Django 5.0.7 on 2024-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_address',
            name='Phone_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
