# Generated by Django 5.0.7 on 2024-08-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_shipping_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_address',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
