# Generated by Django 5.0.7 on 2024-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_alter_order_is_delivered_alter_order_is_placed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CreateAt',
        ),
        migrations.AddField(
            model_name='order',
            name='Create_Date_At',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Create_Time_At',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
