# Generated by Django 5.0.7 on 2024-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_remove_order_createat_order_create_date_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Delivered_At',
        ),
        migrations.AddField(
            model_name='order',
            name='Delivered_Date_At',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Delivered_Time_At',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
