# Generated by Django 5.0.7 on 2024-09-24 05:04

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pamplate',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Pamplates_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pamplates_Image', models.ImageField(blank=True, null=True, upload_to=Products.models.pamplate_image_upload_path)),
                ('Products', models.ManyToManyField(related_name='pamplates', to='Products.product')),
            ],
        ),
    ]
