# Generated by Django 5.0.7 on 2024-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_pamplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamplate',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
