# Generated by Django 5.0.7 on 2024-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_book_page10_image_book_page11_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='product',
            name='Create_Date_At',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Create_Time_At',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
