# Generated by Django 5.0.7 on 2024-08-30 05:48

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_createdat_product_create_date_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Back_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.book_image_upload_path),
        ),
    ]
