# Generated by Django 5.0.7 on 2024-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_book_back_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pamplates',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Pamplates_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Products', models.ManyToManyField(blank=True, related_name='pamplates', to='Products.product')),
            ],
        ),
    ]
