# Generated by Django 5.0.7 on 2024-09-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_pamplates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pamplates',
            name='Products',
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_1', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_2', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_3', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_4', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_5', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_6', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_7', to='Products.product'),
        ),
    ]
