# Generated by Django 5.0.7 on 2024-09-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_pamplates_products_pamplates_product_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamplates',
            name='Product_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_8', to='Products.product'),
        ),
        migrations.AddField(
            model_name='pamplates',
            name='Product_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pamplates_product_9', to='Products.product'),
        ),
    ]
